package main

import (
    "bytes"
    "fmt"
    "go/format"
    "log"
    "os"
    "strings"
)

type Kind int

const (
    // A single switch block. Simple, but slow.
    Flat Kind = iota
    // A lookup table computed at compile-time. Results in a large executable
    // size (adds an extra megabyte), but is exceedingly fast at runtime.
    Lutc
    // A lookup table computed at runtime using a Flat decoder during startup.
    // As fast as Lutc during usage of Decode, but increases program loading
    // time.
    Lutr
)

type Generator struct {
    buf bytes.Buffer
}

func (g *Generator) Printf(format string, args ...interface{}) {
    fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) Generate(pkgName string, kind Kind) {
    g.Printf("// automatically generated by avrmakedec %s\n", strings.Join(os.Args[1:], " "))
    g.Printf("// DO NOT EDIT\n")
    g.Printf("package %s\n", pkgName)
    g.Printf("import \"github.com/kierdavis/avr\"\n")
    switch kind {
    case Flat:
        g.GenerateFlat()
    case Lutc:
        g.GenerateLutc()
    case Lutr:
        g.GenerateLutr()
    default:
        panic("Generator.Generate: bad Kind")
    }
}

func (g *Generator) Format() []byte {
    src, err := format.Source(g.buf.Bytes())
    if err != nil {
        log.Printf("warning: invalid Go generated: %s\n", err)
        log.Printf("warning: compile the package to analyse the error\n")
        return g.buf.Bytes()
    }
    return src
}

